const fs = require('fs');
const path = require('path');
const assert = require('assert');

console.log('=== thebird browser integration test ===\n');

const defaults = JSON.parse(fs.readFileSync(path.join(__dirname, 'docs/defaults.json'), 'utf8'));
['app.js', 'terminal.js', 'agent-chat.js', 'shell.js', 'vendor/thebird-browser.js', 'shell-node.js', 'shell-node-modules.js'].forEach(k => assert(defaults[k], k));
assert(Object.keys(defaults).length > 10);
const indexHtml = fs.readFileSync(path.join(__dirname, 'docs/index.html'), 'utf8');
['pane-chat', 'pane-term', 'pane-preview', 'app.js', 'terminal.js', 'preview-sw-client.js'].forEach(s => assert(indexHtml.includes(s), s));
const previewSw = fs.readFileSync(path.join(__dirname, 'docs/preview-sw.js'), 'utf8');
assert(previewSw.includes('addEventListener') && previewSw.includes('EXPRESS_REQUEST'));
const n = { ...{role:'user',content:'hi'}, content: [{type:'text',text:'hi'}] };
assert(Array.isArray(n.content) && n.content[0].type === 'text' && n.content[0].text === 'hi');
const toolsCode = fs.readFileSync(path.join(__dirname, 'docs/agent-chat.js'), 'utf8');
['read_file','write_file','list_files','run_command','read_terminal','send_to_terminal'].forEach(t => assert(toolsCode.includes(t+':') && toolsCode.includes('parameters:') && toolsCode.includes('execute:'), t));
assert(toolsCode.includes('lastError') && toolsCode.includes('throw'));
const appJs = fs.readFileSync(path.join(__dirname, 'docs/app.js'), 'utf8');
const terminalJs = fs.readFileSync(path.join(__dirname, 'docs/terminal.js'), 'utf8');
assert(appJs.includes('window.__debug') && terminalJs.includes('window.__debug') && toolsCode.includes('window.__debug.agent') && terminalJs.includes('window.__debug.shell') && terminalJs.includes('window.__debug.idbSnapshot'));
assert(terminalJs.includes('1000'));
assert(fs.statSync(path.join(__dirname, 'docs/defaults.json')).size < 100 * 1024 * 1024);
console.log('✓ bootstrap/msgs/tools/__debug/size OK\n');

const nodeEnv = fs.readFileSync(path.join(__dirname, 'docs/shell-node.js'), 'utf8');
['http:','https:','buffer:','child_process:','net:','zlib:','assert:'].forEach(m => assert(nodeEnv.includes(m), m));
const modsJs = fs.readFileSync(path.join(__dirname, 'docs/shell-node-modules.js'), 'utf8');
assert(modsJs.includes('createHttp') && modsJs.includes('httpHandlers[port] = { routes'));
const npmJs = fs.readFileSync(path.join(__dirname, 'docs/shell-npm.js'), 'utf8');
assert(npmJs.includes('esm.sh') && npmJs.includes('?bundle') && nodeEnv.includes('preloadAsyncPkgs') && nodeEnv.includes('pkgCache'));
['install','uninstall','ls','run','init'].forEach(s => assert(npmJs.includes("'" + s + "'"), s));
assert(npmJs.includes('devDependencies') && npmJs.includes('writePkgJson'));
console.log('✓ node builtins + npm subcommands + esm.sh loading\n');

const parserJs = fs.readFileSync(path.join(__dirname, 'docs/shell-parser.js'), 'utf8');
['tokenize','expand','parsePipes','splitTopLevel','parseRedirects'].forEach(fn => assert(parserJs.includes('export function ' + fn)));
const shellMain = fs.readFileSync(path.join(__dirname, 'docs/shell.js'), 'utf8');
assert(shellMain.includes("splitTopLevel(line, ['&&', '||', ';'") && shellMain.includes('parseRedirect'));
const { expand, expandCmdSub } = require('./docs/shell-parser.js');
[['$?', {}, 42, '42'], ['$HOME', { HOME: '/root' }, 0, '/root'], ['${HOME}', { HOME: '/root' }, 0, '/root']].forEach(([t,e,r,v]) => assert(expand(t,e,r) === v, t));
assert(expandCmdSub('pre_$(echo hi)_post', {}, 0, () => 'hi') === 'pre_hi_post');
const builtinsJs = fs.readFileSync(path.join(__dirname, 'docs/shell-builtins.js'), 'utf8');
const builtinsTextJs = fs.readFileSync(path.join(__dirname, 'docs/shell-builtins-text.js'), 'utf8');
['grep','sed','sort','uniq','tr'].forEach(c => assert(builtinsTextJs.includes(c + ':')));
assert(builtinsJs.includes("args[0] === '-e'") && shellMain.includes('varAssigns') && (shellMain.includes('fullExpand') || shellMain.includes('expandCmdSub')));
assert(defaults['shell-builtins-text.js'] && shellMain.includes('const httpHandlers = {}'));
console.log('✓ parser/predictability/httpHandlers OK\n');

{const handlers = {};const routes = { GET: [{ path: '/', fn: (_, res) => res.end('<h1>X</h1>') }] };handlers[3000] = { routes };let body = '';handlers[3000].routes.GET.find(r => r.path === '/').fn({}, { end: b => body = b });assert(body === '<h1>X</h1>');}
['$1', '$#', '$@'].forEach(t => assert(expand(t, {}, 0, ['s','a','b']), t));
const extraJs = fs.readFileSync(path.join(__dirname, 'docs/shell-builtins-extra.js'), 'utf8');
['test',"'['",'tee','xargs','read','printf','shift','local','set','break','continue','source'].forEach(b => assert(extraJs.includes(b), b));
const controlJs = fs.readFileSync(path.join(__dirname, 'docs/shell-control.js'), 'utf8');
['runIf','runWhile','runFor','runCase','defineFn','runSelect','until','elif'].forEach(fn => assert(controlJs.includes(fn), fn));
const rlJs = fs.readFileSync(path.join(__dirname, 'docs/shell-readline.js'), 'utf8');
assert(rlJs.includes('heredocTag') && rlJs.includes('expandBang'));
const exp = require('./docs/shell-expand.js');
assert(exp.evalArith('2+3*4', {}) === 14 && exp.expandBraces('{1..3}').join(',') === '1,2,3' && exp.expandTilde('~/f', { HOME: '/h' }) === '/h/f');
[['${FOO:-x}',{},'x'],['${#X}',{X:'abcde'},'5'],['${X:1:3}',{X:'abcdef'},'bcd'],['${X/o/0}',{X:'food'},'f0od'],['${X%.js}',{X:'foo.js'},'foo'],['$((2+3*4))',{},'14'],['`echo hi`',{},'hi']].forEach(([t,e,v]) => assert(exp.fullExpand(t,e,0,[],()=>'hi') === v, t));
const utilJs = fs.readFileSync(path.join(__dirname, 'docs/shell-builtins-util.js'), 'utf8');
['basename','dirname','realpath','date','find','awk','eval','command',"'[['",'getopts','wait','trap','jobs'].forEach(b => assert(utilJs.includes(b + ':') || utilJs.includes(b), b));
const awk = require('./docs/shell-awk.js'); const sed = require('./docs/shell-sed.js');
assert(awk.runAwk('{print $1}', 'a b\nc d\n') === 'a\nc' && awk.runAwk('BEGIN{print "s"} END{print "e"}', '') === 's\ne' && awk.runAwk('{print NR}', 'x\ny\n') === '1\n2');
assert(sed.runSed(['/^#/d'], '#c\nkeep') === 'keep' && sed.runSed(['s/a/A/', 's/A/B/'], 'a') === 'B');
assert(exp.fullExpand('${arr[@]}',{},0,[],null,{arr:['a','b']}) === 'a b' && exp.fullExpand('${arr[1]}',{},0,[],null,{arr:['a','b']}) === 'b' && exp.fullExpand('${#arr[@]}',{},0,[],null,{arr:['a','b','c']}) === '3');
const parser = require('./docs/shell-parser.js');
assert(parser.globToRe('f[abc]').test('fa') && !parser.globToRe('f[abc]').test('fz') && parser.globToRe('[0-9].js').test('3.js'));
assert(shellMain.includes('bgJobs') && shellMain.includes("'&'") && shellMain.includes('makeExpander') && shellMain.includes('functions:') && shellMain.includes('opts'));
['shell-builtins-extra.js','shell-control.js','shell-expand.js','shell-builtins-util.js','shell-awk.js','shell-sed.js'].forEach(k => assert(defaults[k], k));
console.log('✓ shell features + expansion + awk/sed/arrays/glob/control OK\n');
console.log('✓ awk BEGIN/END/NR/pattern, sed multi -e/d/p, arrays, bracket-glob, bang-history, &, select, trap/jobs\n');

[['${X^^}',{X:'hi'},'HI'],['${X,,}',{X:'HI'},'hi'],['${!X}',{X:'Y',Y:'v'},'v']].forEach(([t,e,v]) => assert(exp.fullExpand(t,e,0,[],null) === v));
assert(exp.fullExpand('${m[k]}', {}, 0, [], null, {m:{k:'v'}}) === 'v');
assert(awk.runAwk('{print length($0)}', 'hello\n') === '5');
assert(sed.runSed(['s/a/A/','tend','s/z/Z/',':end'], 'a\nb') === 'A\nb');
assert(extraJs.includes('-v') && extraJs.includes('declare:'));

global.window = { __debug: { idbSnapshot: {} } };
const sigM = require('./docs/shell-signals.js'), fdM = require('./docs/shell-fd.js'), psM = require('./docs/shell-procsub.js');
const ctx2 = { traps: {}, term: { write() {} }, bgJobs: {}, lastExitCode: 0 };
const sigs = sigM.createSignals(ctx2); sigs.raise('USR1'); assert(sigs.pending()[0] === 'USR1');
const fdt = fdM.createFdTable(ctx2); fdt.open(3, 'f', 'w'); fdt.writeFd(3, 'x'); fdt.dup2(3, 4);
assert(fdt.table[4].duped === 3 && global.window.__debug.idbSnapshot.f === 'x');
const pp = psM.registerStream('data'); assert(psM.readStream(pp.split('/').pop()) === 'data');
['shell-signals.js','shell-jobs.js','shell-fd.js','shell-procsub.js','shell-sw-jobs.js','shell-exec.js'].forEach(k => assert(defaults[k]));
const swJs = fs.readFileSync(path.join(__dirname, 'docs/preview-sw.js'), 'utf8');
assert(swJs.includes('dev') && swJs.includes('tcp') && swJs.includes('procsub') && swJs.includes('JOB_REGISTER'));

const nm = require('./docs/shell-node-modules.js');
assert(nm.NODE_VERSION === 'v23.10.0' && nm.NPM_VERSION === '10.9.2' && nm.NODE_VERSIONS.node === '23.10.0' && Object.keys(nm.NODE_VERSIONS).length >= 25);
const pr = nm.createProcess({ write(){} }, { env: {}, cwd: '/' });
assert(pr.version === 'v23.10.0' && pr.arch === 'x64' && pr.versions.v8.includes('12.9'));
let threw = false; try { pr.exit(3); } catch (e) { threw = e.__nodeExit && e.code === 3; } assert(threw);
let rcv = ''; pr.stdin.on('data', b => rcv += b); pr.stdin._feed('abc'); assert(rcv === 'abc');
const sn = fs.readFileSync(path.join(__dirname, 'docs/shell-node.js'), 'utf8');
assert(sn.includes('stdinBuf') && (sn.includes('require.resolve') || sn.includes('req.resolve')));
assert(sn.includes('__nodeExit') && sn.includes('ctx.lastExitCode'));
assert(npmJs.includes('npm_lifecycle_event') && npmJs.includes("'pre' + scriptName") && npmJs.includes('NPM_VERSION') && npmJs.includes('makeNpx'));
const sxJs = fs.readFileSync(path.join(__dirname, 'docs/shell-exec.js'), 'utf8');
assert(sxJs.includes('makeNodeRunner') && sxJs.includes('NODE_VERSION') && shellMain.includes("'npx'") && shellMain.includes('runNpmResult'));

console.log('=== node parity: util.inspect, crypto, Buffer, fs, ESM, stack, dotenv ===');
global.window = global.window || { __debug: { idbSnapshot: {}, idbPersist: () => {} } };
const stdlibP = 'file:///' + path.resolve('docs/shell-node-stdlib.js').replace(/\\/g, '/');
const ioP = 'file:///' + path.resolve('docs/shell-node-io.js').replace(/\\/g, '/');
const nbP = 'file:///' + path.resolve('docs/node-builtins.js').replace(/\\/g, '/');
(async () => {
  const stdlib = await import(stdlibP); const io = await import(ioP); const nb = await import(nbP);
  assert(stdlib.inspect({a:1,b:[2,3]}) === '{ a: 1, b: [ 2, 3 ] }', 'inspect obj');
  assert(stdlib.inspect([1,2,3]) === '[ 1, 2, 3 ]', 'inspect arr');
  assert(stdlib.inspect(new Map([[1,2]])) === 'Map(1) { 1 => 2 }', 'inspect map');
  assert(stdlib.inspect(null) === 'null' && stdlib.inspect(undefined) === 'undefined' && stdlib.inspect('hi') === "'hi'", 'inspect prim');
  assert(stdlib.format('hi %s %d', 'a', 5) === 'hi a 5', 'format');
  assert(stdlib.createHash('sha256').update('hi').digest('hex') === '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4', 'sha256 hi');
  const Buf = nb.createBuffer();
  assert(Buf.from('hello').toString('hex') === '68656c6c6f', 'hex');
  assert(Buf.concat([Buf.from('ab'), Buf.from('cd')]).toString() === 'abcd', 'concat');
  assert(Buf.alloc(3, 'x').toString() === 'xxx', 'alloc fill');
  const a = Buf.from('hello'), b = Buf.from('hello'), c = Buf.from('world');
  assert(a.equals(b) && !a.equals(c) && a.compare(c) === -1 && a.indexOf('ll') === 2 && a.includes('ell'), 'buffer ops');
  const fs2 = nb.createFs();
  fs2.writeFileSync('t', 'x'); assert(fs2.existsSync('t')); fs2.rmSync('t'); assert(!fs2.existsSync('t'), 'rmSync');
  let threw = false; try { fs2.accessSync('nope'); } catch { threw = true; } assert(threw, 'accessSync');
  assert(io.isEsmCode("import x from 'y'") && io.isEsmCode('export const x=1') && !io.isEsmCode("require('x')"), 'esm detect');
  assert(JSON.stringify(io.parseDotEnv('A=1\nB="two"\n#c\nD=')) === '{"A":"1","B":"two","D":""}', 'dotenv');
  const ctx = { env: {} }; const proc = io.extendProcess({}, ctx);
  assert(proc.execPath === '/usr/local/bin/node' && proc.argv0 === 'node' && ctx.env.PATH && ctx.env.HOME, 'proc extend');
  const stackOut = io.rewriteStack(new Error('boom'), '[eval]');
  assert(stackOut.includes('Error: boom') && stackOut.endsWith('Node.js v23.10.0'), 'stack trailer');
  const sn = fs.readFileSync('docs/shell-node.js', 'utf8');
  assert(sn.includes('isEsmCode') && sn.includes('unhandledrejection') && sn.includes('rewriteStack') && sn.includes('loadDotEnv') && sn.includes("'node:' + k"), 'shell-node wiring');
  ['shell-node-stdlib.js', 'shell-node-io.js', 'shell-node-crypto.js', 'shell-node-resolve.js'].forEach(k => assert(defaults[k], k + ' in defaults'));
  console.log('✓ util.inspect, Buffer full API, fs.rmSync/accessSync, ESM detect, dotenv, stack trailer, node: prefixed specifiers\n');
  console.log('=== node parity pass 3: sha1/512/md5, hmac, pbkdf2, circular refs, exports field, walk-up, REPL ===');
  const cry = await import('file:///' + path.resolve('docs/shell-node-crypto.js').replace(/\\/g, '/'));
  const toHex = bb => [...bb].map(x => x.toString(16).padStart(2, '0')).join('');
  assert(cry.createHash('sha1').update('hi').digest('hex') === 'c22b5f9178342609428d6f51b2c5af4c0bde6a42', 'sha1');
  assert(cry.createHash('sha512').update('hi').digest('hex').startsWith('150a14ed5bea6cc7'), 'sha512');
  assert(cry.createHash('md5').update('hi').digest('hex') === '49f68a5c8493ec2c0bf489821c21fc3b', 'md5');
  assert(cry.createHmac('sha256', 'k').update('m').digest('hex') === 'b60090e3052297aeb5a080889ce2fc4bca957e756faeb4df7d31800ca1e771ec', 'hmac');
  assert(toHex(cry.pbkdf2Sync('pw', 'salt', 1000, 32, 'sha256')) === '0a38253555ce37f5c72a6b703f996814ebf241f203af146e93dcdeb031c5567e', 'pbkdf2');
  assert(cry.randomBytes(8).length === 8, 'randomBytes');
  const obj = { x: 1 }; obj.self = obj;
  assert(stdlib.inspect(obj) === '<ref *1> { x: 1, self: [Circular *1] }', 'circular ref label');
  const rs = await import('file:///' + path.resolve('docs/shell-node-resolve.js').replace(/\\/g, '/'));
  const snap1 = { 'node_modules/pkg/package.json': JSON.stringify({ name: 'pkg', exports: { '.': './lib/main.js' } }), 'node_modules/pkg/lib/main.js': 'module.exports=1' };
  assert(rs.resolvePackageEntry(snap1, '/node_modules/pkg') === '/node_modules/pkg/lib/main.js', 'exports field');
  const snap2 = { 'sub/dir/node_modules/p/index.js': '' };
  assert(rs.walkUpNodeModules(snap2, '/sub/dir/a', 'p') === '/sub/dir/node_modules/p', 'walk-up');
  const e = rs.makeModuleNotFoundError('x'); assert(e.code === 'MODULE_NOT_FOUND', 'MODULE_NOT_FOUND code');
  const fsSync = nb.createFs(); const p = rs.makeFsPromises(fsSync);
  fsSync.writeFileSync('fp', 'hi'); assert(await p.readFile('fp') === 'hi', 'fs.promises'); fsSync.rmSync('fp');
  const net = rs.makeNetStub(); let t2 = false; try { new net.Socket(); } catch { t2 = true; } assert(t2, 'net throws');
  const mm = rs.makeModuleModule(()=>{}, { fs: 1, path: 1 }); assert(mm.builtinModules.includes('fs') && typeof mm.createRequire === 'function', 'module mod');
  assert(sn.includes('setRawMode') && sn.includes("id === 'module'") && sn.includes('walkUpNodeModules') && sn.includes('globalThis.process = proc'), 'wiring3');
  assert(shellMain.includes('.exit') && shellMain.includes('util") .inspect'.replace(' ','')) || shellMain.includes("require(\"util\").inspect"), 'REPL eval');
    globalThis.window = { __debug: { idbSnapshot: {} } };
  const ex = await import('file:///' + path.resolve('docs/shell-node-extras.js').replace(/\\/g, '/'));
  const strm = await import('file:///' + path.resolve('docs/shell-node-streams.js').replace(/\\/g, '/'));
  const cip = await import('file:///' + path.resolve('docs/shell-node-cipher.js').replace(/\\/g, '/'));
  const Buf2 = ex.extendBuffer(nb.createBuffer());
  globalThis.Buffer = Buf2;
  const b64 = Buf2.from([0,0,0,0,0,0,0,42]); assert(b64.readBigUInt64BE(0) === 42n, 'readBigUInt64BE');
  const pathExt = ex.extendPath(nb.createPath());
  assert(pathExt.win32.sep === '\\' && pathExt.win32.join('a','b') === 'a\\b', 'path.win32');
  assert(pathExt.posix.sep === '/', 'path.posix');
  const urlx = ex.createUrlExt();
  assert(urlx.pathToFileURL('/a/b.js').href === 'file:///a/b.js' && urlx.fileURLToPath('file:///a/b.js') === '/a/b.js', 'pathToFileURL');
  const sd = new (ex.makeStringDecoder().StringDecoder)('utf8');
  assert(sd.write(Buffer.from('hi')) === 'hi', 'StringDecoder');
  const als = new (ex.makeAsyncHooks().AsyncLocalStorage)();
  als.run('v', () => assert(als.getStore() === 'v', 'AsyncLocalStorage'));
  const s = strm.makeStream();
  const r = new s.Readable(); const got = [];
  r.on('data', c => got.push(String(c))); r.push('a'); r.push('b'); r.push(null);
  await new Promise(res => r.on('end', res));
  assert(got.join('') === 'ab', 'Readable push');
  const tr = new s.Transform({ transform: (c, e, cb) => cb(null, String(c).toUpperCase()) });
  const out = []; tr.on('data', c => out.push(String(c)));
  tr.write('x'); tr.end();
  await new Promise(res => tr.on('finish', res));
  assert(out[0] === 'X', 'Transform');
  const cry2 = cip.extendCrypto({ pbkdf2Sync: () => new Uint8Array(32) }, Buf2);
  const key = crypto.getRandomValues(new Uint8Array(32)), iv = crypto.getRandomValues(new Uint8Array(16));
  const c1 = cry2.createCipheriv('aes-256-cbc', key, iv); c1.update(Buf2.from('hello'));
  const ct = await c1.final();
  const d1 = cry2.createDecipheriv('aes-256-cbc', key, iv); d1.update(ct);
  assert(new TextDecoder().decode(await d1.final()) === 'hello', 'aes-256-cbc roundtrip');
  assert(cry2.timingSafeEqual(new Uint8Array([1,2]), new Uint8Array([1,2])) === true, 'timingSafeEqual');
  assert(cry2.getCiphers().length >= 6, 'getCiphers');
  const ec = ex.makeErrorCodes(); assert(ec.make('ERR_INVALID_ARG_TYPE').code === 'ERR_INVALID_ARG_TYPE', 'error codes');
  const stubs = ex.makeStubs({}); assert(stubs.cluster.isPrimary === true && stubs.tty.isatty() === true && stubs.sea.isSea() === false, 'stubs');
  console.log('✓ buffer64/path.win32/pathToFileURL/StringDecoder/ALS/Readable/Transform/cipher-roundtrip/errorCodes/stubs\n');

  console.log('=== all checks passed ===');
})().catch(e => { console.error(e); process.exit(1); });
