const fs = require('fs');
const path = require('path');
const assert = require('assert');
const R = (...p) => fs.readFileSync(path.join(__dirname, ...p), 'utf8');
const imp = p => import('file:///' + path.resolve(p).replace(/\\/g, '/'));
const toHex = b => [...b].map(x => x.toString(16).padStart(2, '0')).join('');

console.log('=== thebird integration test ===\n');

const defaults = JSON.parse(R('docs/defaults.json'));
['app.js', 'terminal.js', 'agent-chat.js', 'shell.js', 'vendor/thebird-browser.js', 'shell-node.js', 'shell-node-modules.js', 'shell-node-cipher.js', 'shell-node-keyobject.js', 'shell-node-advanced.js', 'shell-node-observe.js', 'shell-node-runtime.js'].forEach(k => assert(defaults[k] !== undefined, k + ' in defaults'));
['pane-chat', 'pane-term', 'app.js', 'preview-sw-client.js'].forEach(s => assert(R('docs/index.html').includes(s), s));
assert(R('docs/preview-sw.js').includes('EXPRESS_REQUEST'));
['read_file','write_file','run_command','send_to_terminal'].forEach(t => assert(R('docs/agent-chat.js').includes(t + ':'), t));
[R('docs/app.js'), R('docs/terminal.js'), R('docs/agent-chat.js')].forEach(c => assert(c.includes('window.__debug')));
console.log('✓ bootstrap/tools/__debug\n');

const shellMain = R('docs/shell.js');
const { expand, expandCmdSub, globToRe } = require('./docs/shell-parser.js');
[['$?', {}, 42, '42'], ['$HOME', { HOME: '/h' }, 0, '/h'], ['${HOME}', { HOME: '/h' }, 0, '/h']].forEach(([t,e,r,v]) => assert(expand(t,e,r) === v, t));
assert(expandCmdSub('a_$(echo hi)_b', {}, 0, () => 'hi') === 'a_hi_b');
assert(globToRe('f[abc]').test('fa') && !globToRe('f[abc]').test('fz'));
const exp = require('./docs/shell-expand.js');
assert(exp.evalArith('2+3*4') === 14 && exp.expandBraces('{1..3}').join(',') === '1,2,3');
[['${FOO:-x}',{},'x'],['${#X}',{X:'abcde'},'5'],['${X:1:3}',{X:'abcdef'},'bcd'],['${X%.js}',{X:'foo.js'},'foo'],['$((2+3))',{},'5']].forEach(([t,e,v]) => assert(exp.fullExpand(t,e,0,[],()=>'hi') === v, t));
const awk = require('./docs/shell-awk.js'), sed = require('./docs/shell-sed.js');
assert(awk.runAwk('{print $1}', 'a b\nc d\n') === 'a\nc' && awk.runAwk('BEGIN{print "s"}', '') === 's');
assert(sed.runSed(['/^#/d'], '#c\nk') === 'k' && sed.runSed(['s/a/A/'], 'a') === 'A');
console.log('✓ shell parser/expand/awk/sed\n');

global.window = { __debug: { idbSnapshot: {}, idbPersist: () => {} } };
const sigM = require('./docs/shell-signals.js'), fdM = require('./docs/shell-fd.js');
const ctx2 = { traps: {}, term: { write() {} }, bgJobs: {}, lastExitCode: 0 };
sigM.createSignals(ctx2).raise('USR1');
const fdt = fdM.createFdTable(ctx2); fdt.open(3, 'f', 'w'); fdt.writeFd(3, 'x'); fdt.dup2(3, 4);
assert(fdt.table[4].duped === 3 && global.window.__debug.idbSnapshot.f === 'x');
const nm = require('./docs/shell-node-modules.js');
assert(nm.NODE_VERSION === 'v23.10.0' && Object.keys(nm.NODE_VERSIONS).length >= 25);
const pr = nm.createProcess({ write(){} }, { env: {}, cwd: '/' });
let t=false; try { pr.exit(3); } catch (e) { t = e.__nodeExit && e.code === 3; } assert(t);
console.log('✓ signals/fd/process\n');

(async () => {
  const stdlib = await imp('docs/shell-node-stdlib.js');
  const io = await imp('docs/shell-node-io.js');
  const nb = await imp('docs/node-builtins.js');
  const cry = await imp('docs/shell-node-crypto.js');
  const rs = await imp('docs/shell-node-resolve.js');
  const ex = await imp('docs/shell-node-extras.js');
  const strm = await imp('docs/shell-node-streams.js');
  const cip = await imp('docs/shell-node-cipher.js');
  const ko = await imp('docs/shell-node-keyobject.js');
  const adv = await imp('docs/shell-node-advanced.js');
  const ob = await imp('docs/shell-node-observe.js');
  const rt = await imp('docs/shell-node-runtime.js');

  assert(stdlib.inspect({a:1,b:[2,3]}) === '{ a: 1, b: [ 2, 3 ] }');
  assert(stdlib.inspect(10n) === '10n' && stdlib.inspect({[Symbol('k')]:'v'}).includes('Symbol(k)') && stdlib.inspect(42,{colors:true}).includes('\x1b[33m'));
  assert(stdlib.format('hi %s %d', 'a', 5) === 'hi a 5');

  assert(cry.createHash('sha1').update('hi').digest('hex') === 'c22b5f9178342609428d6f51b2c5af4c0bde6a42');
  assert(cry.createHash('md5').update('hi').digest('hex') === '49f68a5c8493ec2c0bf489821c21fc3b');
  assert(cry.createHmac('sha256', 'k').update('m').digest('hex') === 'b60090e3052297aeb5a080889ce2fc4bca957e756faeb4df7d31800ca1e771ec');
  assert(toHex(cry.pbkdf2Sync('pw', 'salt', 1000, 32, 'sha256')) === '0a38253555ce37f5c72a6b703f996814ebf241f203af146e93dcdeb031c5567e');

  assert(rs.resolveExports({exports:{'.':{import:'./e.js',require:'./c.js'}}}, '.') === './e.js');
  assert(rs.resolveImports({imports:{'#i/*':'./l/*.js'}}, '#i/x') === './l/x.js');
  assert(rs.makeModuleNotFoundError('x').code === 'MODULE_NOT_FOUND');

  const Buf = ex.extendBuffer(nb.createBuffer());
  globalThis.Buffer = Buf;
  assert(Buf.from('hello').toString('hex') === '68656c6c6f');
  assert(Buf.from([0,0,0,0,0,0,0,42]).readBigUInt64BE(0) === 42n);
  const pathExt = ex.extendPath(nb.createPath());
  assert(pathExt.win32.sep === '\\' && pathExt.win32.join('a','b') === 'a\\b' && pathExt.posix.sep === '/');
  const urlx = ex.createUrlExt();
  assert(urlx.pathToFileURL('/a/b.js').href === 'file:///a/b.js' && urlx.fileURLToPath('file:///a/b.js') === '/a/b.js');
  const als = new (ex.makeAsyncHooks().AsyncLocalStorage)();
  als.run('v', () => assert(als.getStore() === 'v'));

  const s = strm.makeStream();
  const r = new s.Readable(); const got = [];
  r.on('data', c => got.push(String(c))); r.push('a'); r.push('b'); r.push(null);
  await new Promise(res => r.on('end', res));
  assert(got.join('') === 'ab');
  const tr = new s.Transform({ transform: (c, e, cb) => cb(null, String(c).toUpperCase()) });
  const tout = []; tr.on('data', c => tout.push(String(c)));
  tr.write('x'); tr.end();
  await new Promise(res => tr.on('finish', res));
  assert(tout[0] === 'X');
  console.log('✓ stdlib/crypto/resolve/buffer/path/url/ALS/streams\n');

  globalThis.crypto = require('crypto').webcrypto;
  const c6 = ko.extendKeys(cip.extendCrypto({}, Buf));
  const rsaKp = await c6.generateKeyPairAsync('rsa', { modulusLength: 2048 });
  const rsig = await c6.signAsync('RSA-SHA256', 'data', rsaKp.privateKey);
  assert(await c6.verifyAsync('RSA-SHA256', 'data', rsaKp.publicKey, rsig));
  const ecKp = await c6.generateKeyPairAsync('ec', { namedCurve: 'P-256' });
  const esig = await c6.signAsync('sha256', Buffer.from('d'), ecKp.privateKey);
  assert(await c6.verifyAsync('sha256', Buffer.from('d'), ecKp.publicKey, esig));
  const hk = await c6.hkdfAsync('sha256', Buffer.from('i'), Buffer.from('s'), Buffer.from('f'), 32);
  assert(hk.length === 32);
  const dh1 = c6.createECDH('prime256v1'), dh2 = c6.createECDH('prime256v1');
  const p1 = await dh1.generateKeys(), p2 = await dh2.generateKeys();
  assert((await dh1.computeSecret(p2)).equals(await dh2.computeSecret(p1)));
  assert(c6.createPrivateKey(ecKp.privateKey).asymmetricKeyType === 'ec');
  const key = crypto.getRandomValues(new Uint8Array(32)), iv = crypto.getRandomValues(new Uint8Array(16));
  const c1 = c6.createCipheriv('aes-256-cbc', key, iv); c1.update(Buf.from('hello'));
  const ct = await c1.final();
  const d1 = c6.createDecipheriv('aes-256-cbc', key, iv); d1.update(ct);
  assert(new TextDecoder().decode(await d1.final()) === 'hello');
  assert(c6.getCiphers().length >= 6);
  console.log('✓ RSA/ECDSA/HKDF/ECDH/KeyObject/AES\n');

  const diag = ob.makeDiagnosticsChannel(); let dgot = null;
  diag.channel('t').subscribe(m => { dgot = m; }); diag.channel('t').publish({n: 7});
  assert(dgot?.n === 7 && diag.hasSubscribers('t'));
  const reg6 = ob.makeDebugRegistry();
  const te6 = ob.makeTraceEvents(reg6); te6.createTracing({categories:['c']}).enable();
  assert(te6.getEnabledCategories().includes('c'));
  assert(ob.makeProcessBindings()('util').isDate(new Date()) === true);
  let bt = false; try { ob.makeProcessBindings()('unknown'); } catch { bt = true; } assert(bt);
  assert(typeof ob.makePerfMemory({})().heapUsed === 'number');
  assert(new (ob.makeFetchPool())({maxSockets:2}).maxSockets === 2);
  ob.installPrepareStackTraceHook();
  Error.prepareStackTrace = (e, frames) => frames.length;
  assert(typeof new Error('x').stack === 'number');
  Error.prepareStackTrace = null;
  console.log('✓ diag/trace/binding/memory/agent/prepareStack\n');

  assert(adv.makeVmModule().runInThisContext('2+2') === 4);
  const mr = adv.makeModuleRegister();
  assert(typeof mr.register === 'function' && Array.isArray(mr._hooks));
  assert(typeof adv.makeHttp2().connect === 'function' && adv.makeHttp2().constants.HTTP2_HEADER_METHOD === ':method');
  assert(typeof new (adv.makeWasi().WASI)({}).start === 'function');
  const repl = rt.makeRepl({}, {write:()=>{}}, async()=>{});
  assert(repl.isIncomplete('function f() {') === true && repl.isIncomplete('2 + 2') === false);
  assert(typeof rt.makeWorkerThreads(()=>({}),Buf).Worker === 'function');
  assert(typeof rt.makeChildProcessReal(Buf, s).exec === 'function');
  assert([[],[new Error('x',{cause:new Error('y')}).cause.message==='y','cause'],[new AggregateError([new Error('a')],'m').errors.length===1,'aggr']].slice(1).every(([v])=>v));
  console.log('✓ vm/register/http2/wasi/repl/workers/cp/Error.cause\n');

  console.log('=== pass 7: Firefox + polyfills ===');
  const ff7 = await imp('docs/shell-node-firefox.js'), n7 = await imp('docs/shell-node-net.js'), prof7 = await imp('docs/shell-node-profiler.js'), clu7 = await imp('docs/shell-node-cluster.js'), ins7 = await imp('docs/shell-node-inspector.js');
  const info7 = ff7.detectBrowser();
  assert(typeof info7.vendor === 'string' && Object.keys(info7.capabilities).length >= 10, 'browser detect');
  const Bf = Buf;
  const nm7 = n7.makeNet(Bf);
  assert(typeof nm7.Socket === 'function' && nm7.isIP('1.2.3.4') === 4, 'net');
  const tm7 = n7.makeTls(nm7, Bf);
  assert(new tm7.TLSSocket() instanceof nm7.Socket && tm7.DEFAULT_MIN_VERSION === 'TLSv1.2', 'tls');
  assert(typeof n7.makeDgram(Bf).createSocket('udp4').send === 'function', 'dgram');
  const v7 = prof7.makeV8Profiler({}); const cp7 = new v7.CPUProfile(); cp7.startProfiling('t'); cp7.stopProfiling();
  assert(Array.isArray(cp7.nodes) && typeof v7.getHeapStatistics().used_heap_size === 'number', 'v8');
  global.window = { __debug: { idbSnapshot: {} } };
  prof7.makeHeapSnapshot().writeHeapSnapshot('s.heapsnapshot');
  const hp = JSON.parse(global.window.__debug.idbSnapshot['s.heapsnapshot']);
  assert(Array.isArray(hp.snapshot.meta.node_fields) && hp.nodes.length > 0, 'heap snapshot');
  const c7 = clu7.makeCluster();
  assert(c7 === null || typeof c7.isMaster === 'boolean', 'cluster');
  const i7 = ins7.makeInspector({}); const opened = i7.open(9229, '127.0.0.1', false);
  assert(opened.url.startsWith('ws://') && typeof i7.Session === 'function', 'inspector');
  console.log('✓ UA/capabilities/net/tls/dgram/v8/heap/cluster/inspector\n');

  console.log('=== pass 8: runtime parity + POSIX ===');
  const rt8 = await imp('docs/shell-runtime.js'), dn8 = await imp('docs/shell-deno.js'), bn8 = await imp('docs/shell-bun.js'), pm8 = await imp('docs/shell-pm.js'), ts8 = await imp('docs/shell-ts.js'), px8 = await imp('docs/shell-posix.js'), rs8 = await imp('docs/shell-node-resolve.js');
  const r8 = rt8.detectRuntime();
  assert(typeof r8.runtime === 'string' && typeof r8.features === 'object', 'runtime');
  [[rt8.switchRuntime('#!/usr/bin/env deno')==='deno','deno sh'],[rt8.switchRuntime('#!/usr/bin/env bun')==='bun','bun sh'],[rt8.switchRuntime('')==='node','default sh'],[rs8.rewriteSpecifier('jsr:@f/b')==='https://esm.sh/jsr/@f/b','jsr'],[rs8.rewriteSpecifier('npm:p@1')==='https://esm.sh/p@1','npm'],[pm8.detectPm({'pnpm-lock.yaml':'x'}).pm==='pnpm','pnpm'],[pm8.detectPm({'bun.lock':'x'}).pm==='bun','bun lock'],[pm8.detectPm({'yarn.lock':'x'}).pm==='yarn','yarn'],[pm8.detectPm({'package.json':'{"packageManager":"pnpm@9"}'}).pm==='pnpm','pm field'],[ts8.isTsFile('a.ts')&&!ts8.isTsFile('a.js'),'ts file'],[!ts8.stripTypesSync('const x: number = 5;').includes(': number'),'ts strip']].forEach(([v,n])=>assert(v,n));
  global.window = { __debug: { idbSnapshot: {}, idbPersist: () => {} } };
  const fsP = await import('file:///' + path.resolve('docs/node-builtins.js').replace(/\\/g, '/'));
  const pfs = fsP.createFs();
  px8.installPosixFs(pfs, Buf, { umask: 0o022 });
  px8.installFds(pfs, Buf);
  px8.installTmpAndMisc(pfs, Buf, { umask: 0o022 });
  pfs.writeFileSync('/a', 'hello');
  pfs.symlinkSync('/a', '/b');
  assert(pfs.readlinkSync('/b') === '/a', 'readlink');
  assert(pfs.readFileSync('/b').toString() === 'hello', 'follow symlink');
  assert(pfs.lstatSync('/b').isSymbolicLink() === true, 'lstat link');
  assert(pfs.statSync('/b').isFile() === true, 'stat follows');
  pfs.chmodSync('/a', 0o755);
  assert((pfs.statSync('/a').mode & 0o777) === 0o755, 'chmod');
  const fdX = pfs.openSync('/c', 'w+');
  pfs.writeSync(fdX, Buf.from('xy'), 0, 2, 0);
  pfs.closeSync(fdX);
  assert(pfs.readFileSync('/c').toString() === 'xy', 'fd write');
  const tmpD = pfs.mkdtempSync('/tmp/t-');
  assert(tmpD.startsWith('/tmp/t-') && pfs.existsSync(tmpD), 'mkdtemp');
  const procMock = { pid: 1, env: { HOME: '/root' }, argv: ['node'], exit: () => {}, cwd: () => '/', on: () => {}, memoryUsage: () => ({}) };
  const dg = dn8.makeDenoGlobal(pfs, procMock, { exec: () => {} }, {}, Buf);
  assert(dg.readTextFileSync('/a') === 'hello' && dg.env.get('HOME') === '/root', 'Deno shim');
  const bg = bn8.makeBunGlobal(pfs, procMock, { exec: () => {} }, {}, Buf, { Readable: class R{} }, {});
  assert(await bg.file('/a').text() === 'hello' && typeof bg.version === 'string', 'Bun shim');
  console.log('✓ runtime/jsr/pm/ts/symlink/fd/mkdtemp/Deno/Bun\n');
  console.log('=== all checks passed ===');
})().catch(e => { console.error(e); process.exit(1); });
